### ISSUE TITLE
Exception while executing the query

### ISSUE THREAD

**Issue by nikhilt44** [ixa-ehu/ixa-pipe-wikify#2]
When I execute the command, 
cat test.txt | ixa-pipe-tok | ixa-pipe-pos | java -jar ixa-pipe-wikify-1.4.0.jar -p 2020

I get the following error,

ixa-pipe-tok: command not found
ixa-pipe-pos: command not found
Exception in thread "main" org.jdom2.input.JDOMParseException: Error on line -1: Premature end of file.
    at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:232)
    at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)
    at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1196)
    at ixa.kaflib.ReadWriteManager.load(ReadWriteManager.java:52)
    at ixa.kaflib.KAFDocument.createFromStream(KAFDocument.java:411)
    at ixa.pipe.wikify.CLI.parseCLI(CLI.java:145)
    at ixa.pipe.wikify.CLI.main(CLI.java:59)
Caused by: org.xml.sax.SAXParseException; Premature end of file.
    at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
    at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
    ... 6 more

**Comment by antxa** [comment]
As described in the readme, the ixa-pipe-wikify requires a NAF document (with wf and term elements) as standard input. And you can get the necessary NAF input for ixa-pipe-wikify by piping ixa-pipe-tok and ixa-pipe-pos.
That means that when running the command 
     cat test.txt | ixa-pipe-tok | ixa-pipe-pos | java -jar ixa-pipe-wikify-1.4.0.jar
you have to replace ixa-pipe-tok and ixa-pipe-pos with the commands to run those tools. You can find more information about how to run those tools in the following links:
https://github.com/ixa-ehu/ixa-pipe-tok
https://github.com/ixa-ehu/ixa-pipe-pos

Arantxa

**Comment by nikhilt44** [comment]
Thanks for the help. I was able to make it work

**Comment by nikhilt44** [comment]
I wanted to clarify one point, this tool links entities in the input text to Wikipedia Pages, right?

**Comment by ixa-ehu** [comment]
This tool annotates any mention (not only named entities) of DBpedia in the text. So, it doesn't link directly to Wikipedia.
